name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version string'
        required: true
        default: '0.0.0'
      body:
        description: 'Release body'
        required: true
        default: 'Release body'
env:
  BUILD_TYPE: Release
  SERV_BIN: rtype_server
  CLIENT_BIN: rtype_client

  VCPKG_DISABLE_METRICS: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ windows-latest, ubuntu-latest, macos-latest ]
        include:
          - platform: windows-latest
            triplet: x64-windows
          - platform: ubuntu-latest
            triplet: x64-linux
          - platform: macos-latest
            triplet: x64-osx
    runs-on: ${{ matrix.platform }}
    env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    environment:
      name: production
    permissions:
      contents: read
    steps:
      - name: Install system deps for Linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update -y && sudo apt upgrade -y
          sudo apt install -y libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev autoconf libtool

      - name: Nuget install WiX
        if: matrix.platform == 'windows-latest'
        run: nuget install WiX
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '${{ env.VCPKG_COMMIT }}'

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure
        shell: cmake -P {0}
        run: |
          cmake_path(SET VCPKG_TOOLCHAIN_PATH ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake)
          message(STATUS "Using vcpkg.cmake in: ${VCPKG_TOOLCHAIN_PATH}")
          cmake_path(SET SFML_DIR ${{ github.workspace }}/vcpkg/installed/${{ matrix.triplet }}/share/sfml)
          message(STATUS "Using SFML_DIR: ${SFML_DIR}")
          if (${{ matrix.platform }} STREQUAL "windows-latest")
            execute_process(
              COMMAND cmake
                -S .
                -B build
                -G "Visual Studio 17 2022"
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
                -DCMAKE_TOOLCHAIN_FILE=${VCPKG_TOOLCHAIN_PATH}
                -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE
            RESULT_VARIABLE result
            )
          else()
            execute_process(
              COMMAND cmake
                -S .
                -B build
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
                -DCMAKE_TOOLCHAIN_FILE=${VCPKG_TOOLCHAIN_PATH}
              RESULT_VARIABLE result
            )
          endif()
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status. Failed to configure RTYPE project.")
          endif()

      - name: Build
        shell: cmake -P {0}
        run: |
          message(STATUS "Using host CMake version: ${CMAKE_VERSION}")

          execute_process(
            COMMAND cmake --build build
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status. Failed to build RTYPE project.")
          endif()

      - name: Debug list windows directory
        if: matrix.platform == 'windows-latest'
        shell: bash
        run: |
          ls -lRa
      - name: Package
        shell: cmake -P {0}
        if: matrix.platform == 'ubuntu-latest'
        run: |
          execute_process(
            COMMAND cpack 
            WORKING_DIRECTORY build
            RESULT_VARIABLE result
          )

          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status. Failed to build RTYPE project.")
          endif()
      - name: Create msi installer
        if: matrix.platform == 'windows-latest'
        run: |
          cd build
          cpack -G WIX -C Debug
      - name: Upload Linux artifact
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/build/rtype-*-Linux.tar.gz
            ${{ github.workspace }}/build/rtype-*-Linux.rpm
            ${{ github.workspace }}/build/rtype-*-Linux.deb
      - name: Upload Windows artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/build/rtype-*-win64.msi  

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Debug list directory
        shell: bash
        run: |
          ls -lRa

      - name: Upload release binaries
        id: upload_release_asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.event.inputs.version }}" -t "${{ github.event.inputs.version }}"  -n "${{ github.event.inputs.body }}" ${{ github.workspace }}/ubuntu-latest/* ${{ github.workspace }}/windows-latest/*
